from PySide6.QtGui import QPixmap, QFontDatabase, QAction, QIcon
from PySide6.QtWidgets import QApplication, QWidget, QVBoxLayout, QLabel, QSizePolicy, QHBoxLayout, QLineEdit, \
    QRadioButton, QPushButton, QMenu, QMenuBar
from PySide6.QtCore import QFile, QTextStream, Qt


# Function to load QSS file
def load_stylesheet(file_path):
    file = QFile(file_path)
    if not file.open(QFile.ReadOnly):
        raise Exception(f"Cannot open file: {file_path}")
    stream = QTextStream(file)
    stylesheet = stream.readAll()
    file.close()
    return stylesheet


class HermesApp(QWidget):
    """Main application window for Hermes."""

    def __init__(self):
        super().__init__()
        self.init_ui()

    def init_ui(self):
        self.load_resources()
        self.setup_menu()
        self.create_layouts()
        self.create_widgets()
        self.setup_layouts()
        self.apply_stylesheet()
        self.setup_window()

    def load_resources(self):
        """Loads application resources (icons, fonts)."""
        app = QApplication.instance()
        app.setWindowIcon(QIcon("/resources/images/Logo.ico"))
        QFontDatabase.addApplicationFont(
            "/resources/images/Font_005.ttf")
        QFontDatabase.addApplicationFont(
            "/resources/images/LEMONMILK-Medium.otf")

    def apply_stylesheet(self):
        """Applies the application stylesheet."""
        app = QApplication.instance()
        stylesheet = load_stylesheet("../resources/style_test_001.qss")
        app.setStyleSheet(stylesheet)

    def setup_menu(self):
        """Sets up the application menu bar."""
        self.menu_bar = QMenuBar()
        self.menu_bar.setObjectName("menu")
        file_menu = QMenu("File", self.menu_bar)
        self.menu_bar.addMenu(file_menu)
        new_action = QAction("New", self)
        open_action = QAction("Open", self)
        save_action = QAction("Save", self)
        exit_action = QAction("Exit", self)
        exit_action.triggered.connect(QApplication.instance().quit)
        file_menu.addAction(new_action)
        file_menu.addAction(open_action)
        file_menu.addAction(save_action)
        file_menu.addSeparator()
        file_menu.addAction(exit_action)
        edit_menu = QMenu("Edit", self.menu_bar)
        self.menu_bar.addMenu(edit_menu)
        view_menu = QMenu("View", self.menu_bar)
        self.menu_bar.addMenu(view_menu)
        help_menu = QMenu("Help", self.menu_bar)
        self.menu_bar.addMenu(help_menu)

    def create_layouts(self):
        """Creates main layouts."""
        self.window_layout = QVBoxLayout()
        self.main_content_layout = QHBoxLayout()
        self.left_layout = QHBoxLayout()
        self.sidebar_layout = QVBoxLayout()
        self.sidebarInnards_layout = QVBoxLayout()
        self.right_layout = QVBoxLayout()
        self.topRight_layout = QVBoxLayout()
        self.bottomRight_layout = QVBoxLayout()
        self.interact_layout = QHBoxLayout()
        self.tab_layout = QVBoxLayout()
        self.box_layout = QHBoxLayout()
        self.tabBottom_layout = QVBoxLayout()
        self.boxBottom_layout = QHBoxLayout()
        self.plant_layout = QVBoxLayout()
        self.plantInputs_layout = QHBoxLayout()
        self.plantInputsLeft_layout = QVBoxLayout()
        self.plantInputsRight_layout = QVBoxLayout()
        self.turbine_layout = QVBoxLayout()
        self.turbineInputs_layout = QHBoxLayout()
        self.turbineInputsLeft_layout = QVBoxLayout()
        self.turbineInputsRight_layout = QVBoxLayout()
        self.weather_layout = QVBoxLayout()
        self.weatherInputs_layout = QHBoxLayout()
        self.weatherInputsLeft_layout = QVBoxLayout()
        self.weatherInputsRight_layout = QVBoxLayout()
        self.block_layout = QVBoxLayout()
        self.rack_layout = QVBoxLayout()
        self.module_layout = QVBoxLayout()
        self.cell_layout = QVBoxLayout()

    def create_widgets(self):
        """Creates all widgets."""
        self.left = QWidget()
        self.left.setObjectName("left")
        self.sidebar = QWidget()
        self.sidebar.setObjectName("sidebar")
        self.sidebarInnards = QWidget()
        self.sidebarInnards.setObjectName("sidebarInnards")
        self.sidebarLogo = QLabel("H")
        self.sidebarLogo.setObjectName("sidebarLogo")
        self.sidebarDescription = QLabel(
            "Generate fully customizable plant and weather configurations to simulate the behavior of a BESS-BMS.")
        self.sidebarDescription.setObjectName("sidebarDescription")
        self.sidebarButton1 = QPushButton("Save")
        self.sidebarButton1.setObjectName("sidebarButton1")
        self.sidebarButton2 = QPushButton("Button2")
        self.sidebarButton2.setObjectName("sidebarButton2")
        self.sidebarButton3 = QPushButton("Button3")
        self.sidebarButton3.setObjectName("sidebarButton3")
        self.sidebarCollapse = QPushButton("❰")
        self.sidebarCollapse.setObjectName("collapse")
        self.sidebarSpace = QLabel("")
        self.sidebarSpace.setObjectName("sidebarSpace")
        self.right = QWidget()
        self.right.setObjectName("right")
        self.topRight = QWidget()
        self.topRight.setObjectName("topRight")
        self.bottomRight = QWidget()
        self.bottomRight.setObjectName("bottomRight")
        self.interact = QWidget()
        self.interact.setObjectName("interact")
        self.interactInput = QLineEdit()
        self.interactInput.setPlaceholderText("Filename")
        self.interactInput.setObjectName("interactInput")
        self.interactButton = QPushButton("Next")
        self.interactButton.setObjectName("interactButton")
        self.tab = QWidget()
        self.tab.setObjectName("tab")
        self.box = QWidget()
        self.box.setObjectName("box")
        self.tabBottom = QWidget()
        self.tabBottom.setObjectName("tabBottom")
        self.boxBottom = QWidget()
        self.boxBottom.setObjectName("boxBottom")
        self.plant = QWidget()
        self.plant.setObjectName("plant")
        self.plantTitle = QLabel("Plant Size")
        self.plantTitle.setObjectName("plantTitle")
        self.plantIcon = QLabel("A")
        self.plantIcon.setObjectName("plantIcon")
        self.plantParameters = QLabel("Parameters")
        self.plantParameters.setObjectName("plantParameters")
        self.plantInputs = QWidget()
        self.plantInputs.setObjectName("plantInputs")
        self.plantInputsLeft = QWidget()
        self.plantInputsLeft.setObjectName("plantInputsLeft")
        self.plantInputsLeftNumberTitle = QLabel("Number of Turbines")
        self.plantInputsLeftNumberTitle.setObjectName("plantInputsLeftNumberTitle")
        self.plantInputsLeftNumberInput = QLineEdit()
        self.plantInputsLeftNumberInput.setObjectName("plantInputsLeftNumberInput")
        self.plantInputsRight = QWidget()
        self.plantInputsRight.setObjectName("plantInputsRight")
        self.plantInputsLeftLocationTitle = QRadioButton("On-shore")
        self.plantInputsLeftLocationTitle.setObjectName("plantInputsLeftLocationTitle")
        self.plantInputsLeftLocationInput = QRadioButton("Off-shore")
        self.plantInputsLeftLocationInput.setObjectName("plantInputsLeftLocationInput")

        self.turbine = QWidget()
        self.turbine.setObjectName("turbine")
        self.turbineTitle = QLabel("Turbine Configuration")
        self.turbineTitle.setObjectName("turbineTitle")
        self.turbineIcon = QLabel("B")
        self.turbineIcon.setObjectName("turbineIcon")
        self.turbineParameters = QLabel("Parameters")
        self.turbineParameters.setObjectName("turbineParameters")
        self.turbineInputs = QWidget()
        self.turbineInputs.setObjectName("turbineInputs")
        self.turbineInputsLeft = QWidget()
        self.turbineInputsLeft.setObjectName("turbineInputsLeft")
        self.turbineInputsLeftNumberTitle = QLabel("Blade Length")
        self.turbineInputsLeftNumberTitle.setObjectName("turbineInputsLeftNumberTitle")
        self.turbineInputsLeftNumberInput = QLineEdit()
        self.turbineInputsLeftNumberInput.setObjectName("turbineInputsLeftNumberInput")
        self.turbineInputsRight = QWidget()
        self.turbineInputsRight.setObjectName("turbineInputsRight")
        self.turbineInputsLeftLocationTitle = QLabel("Energy Coefficient")
        self.turbineInputsLeftLocationTitle.setObjectName("turbineInputsLeftLocationTitle")
        self.turbineInputsLeftLocationInput = QLineEdit()
        self.turbineInputsLeftLocationInput.setPlaceholderText("Max = 0.59")
        self.turbineInputsLeftLocationInput.setObjectName("turbineInputsLeftLocationInput")
        self.weather = QWidget()
        self.weather.setObjectName("weather")
        self.weatherTitle = QLabel("Weather")
        self.weatherTitle.setObjectName("weatherTitle")
        self.weatherIcon = QLabel("C")
        self.weatherIcon.setObjectName("weatherIcon")
        self.weatherParameters = QLabel("Parameters")
        self.weatherParameters.setObjectName("weatherParameters")
        self.weatherInputs = QWidget()
        self.weatherInputs.setObjectName("weatherInputs")
        self.weatherInputsLeft = QWidget()
        self.weatherInputsLeft.setObjectName("weatherInputsLeft")
        self.weatherInputsLeftNumberTitle = QLabel("Min. Wind Speed")
        self.weatherInputsLeftNumberTitle.setObjectName("weatherInputsLeftNumberTitle")
        self.weatherInputsLeftNumberInput = QLineEdit()
        self.weatherInputsLeftNumberInput.setObjectName("weatherInputsLeftNumberInput")
        self.weatherInputsRight = QWidget()
        self.weatherInputsRight.setObjectName("weatherInputsRight")
        self.weatherInputsLeftLocationTitle = QLabel("Max. Wind Speed")
        self.weatherInputsLeftLocationTitle.setObjectName("weatherInputsLeftLocationTitle")
        self.weatherInputsLeftLocationInput = QLineEdit()
        self.weatherInputsLeftLocationInput.setPlaceholderText("Max = 40")
        self.weatherInputsLeftLocationInput.setObjectName("weatherInputsLeftLocationInput")
        self.block = QWidget()
        self.block.setObjectName("block")
        self.blockIcon = QLabel("D")
        self.blockIcon.setObjectName("blockIcon")
        self.blockTitle = QLabel("Block")
        self.blockTitle.setObjectName("blockTitle")
        self.blockInput = QLineEdit()
        self.blockInput.setPlaceholderText("Max = 10")
        self.blockInput.setObjectName("blockInput")
        self.rack = QWidget()
        self.rack.setObjectName("rack")
        self.rackIcon = QLabel("E")
        self.rackIcon.setObjectName("rackIcon")
        self.rackTitle = QLabel("Rack")
        self.rackTitle.setObjectName("rackTitle")
        self.rackInput = QLineEdit()
        self.rackInput.setPlaceholderText("Max = 10")
        self.rackInput.setObjectName("rackInput")
        self.module = QWidget()
        self.module.setObjectName("module")
        self.moduleIcon = QLabel("F")
        self.moduleIcon.setObjectName("moduleIcon")
        self.moduleTitle = QLabel("Module")
        self.moduleTitle.setObjectName("moduleTitle")
        self.moduleInput = QLineEdit()
        self.moduleInput.setPlaceholderText("Max = 10")
        self.moduleInput.setObjectName("moduleInput")
        self.cell = QWidget()
        self.cell.setObjectName("cell")
        self.cellIcon = QLabel("G")
        self.cellIcon.setObjectName("cellIcon")
        self.cellTitle = QLabel("Cell")
        self.cellTitle.setObjectName("cellTitle")
        self.cellInput = QLineEdit()
        self.cellInput.setPlaceholderText("Max = 10")
        self.cellInput.setObjectName("cellInput")
        self.titleTop = QLabel("Plant Configuration")
        self.titleTop.setObjectName("titleTop")
        self.titleBottom = QLabel("BESS Configuration")
        self.titleBottom.setObjectName("titleBottom")

    def setup_layouts(self):
        """Sets up the layouts for all widgets."""
        self.setLayout(self.window_layout)
        self.window_layout.addWidget(self.menu_bar)
        self.main_content_layout.addWidget(self.left, stretch=1)
        self.main_content_layout.addWidget(self.right, stretch=4)
        self.main_content_layout.setAlignment(Qt.AlignCenter)
        self.window_layout.addLayout(self.main_content_layout)
        self.left.setLayout(self.left_layout)
        self.left_layout.addWidget(self.sidebar, stretch=1)
        self.sidebar.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.sidebar.setLayout(self.sidebar_layout)
        self.sidebar_layout.setAlignment(Qt.AlignCenter)
        self.sidebar_layout.addWidget(self.sidebarInnards, stretch=1)
        self.sidebarInnards.setLayout(self.sidebarInnards_layout)
        self.sidebarInnards_layout.setAlignment(Qt.AlignCenter)
        self.sidebarInnards_layout.addWidget(self.sidebarCollapse, stretch=1)
        self.sidebarInnards_layout.addWidget(self.sidebarLogo, stretch=3)
        self.sidebarInnards_layout.addWidget(self.sidebarDescription, stretch=3)
        self.sidebarInnards_layout.addWidget(self.sidebarButton1, stretch=1, alignment=Qt.AlignCenter)
        self.sidebarInnards_layout.addWidget(self.sidebarButton2, stretch=1, alignment=Qt.AlignCenter)
        self.sidebarInnards_layout.addWidget(self.sidebarButton3, stretch=1, alignment=Qt.AlignCenter)
        self.sidebarInnards_layout.addWidget(self.sidebarSpace, stretch=3)
        self.sidebarInnards_layout.setSpacing(0)
        self.sidebarInnards.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.sidebarSpace.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.right.setLayout(self.right_layout)
        self.right_layout.addWidget(self.topRight, stretch=6)
        self.right_layout.addWidget(self.bottomRight, stretch=6)
        self.right_layout.addWidget(self.interact, stretch=1)
        self.topRight.setLayout(self.topRight_layout)
        self.topRight_layout.addWidget(self.tab, stretch=1)
        self.topRight_layout.addWidget(self.box, stretch=8)
        self.topRight.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        self.bottomRight.setLayout(self.bottomRight_layout)
        self.bottomRight_layout.addWidget(self.tabBottom, stretch=1)
        self.bottomRight_layout.addWidget(self.boxBottom, stretch=8)
        self.bottomRight.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        self.interact.setLayout(self.interact_layout)
        self.interact_layout.addWidget(self.interactInput, stretch=9)
        self.interact_layout.addWidget(self.interactButton, stretch=2)
        self.tab.setLayout(self.tab_layout)
        self.tab_layout.addWidget(self.titleTop, stretch=1)
        self.tab_layout.addWidget(self.box, stretch=8)
        self.box.setLayout(self.box_layout)
        self.box_layout.addWidget(self.plant, stretch=1)
        self.box_layout.addWidget(self.turbine, stretch=1)
        self.box_layout.addWidget(self.weather, stretch=1)
        self.tabBottom.setLayout(self.tabBottom_layout)
        self.tabBottom_layout.addWidget(self.titleBottom, stretch=1)
        self.tabBottom_layout.addWidget(self.boxBottom, stretch=8)
        self.boxBottom_layout.addWidget(self.block, stretch=1)
        self.boxBottom_layout.addWidget(self.rack, stretch=1)
        self.boxBottom_layout.addWidget(self.module, stretch=1)
        self.boxBottom_layout.addWidget(self.cell, stretch=1)
        self.boxBottom_layout.setSpacing(0)
        self.plant.setLayout(self.plant_layout)
        self.plant_layout.addWidget(self.plantTitle, stretch=1)
        self.plant_layout.addWidget(self.plantIcon, stretch=4)
        self.plant_layout.addWidget(self.plantInputs, stretch=2)
        self.plantInputs.setLayout(self.plantInputs_layout)
        self.plantInputs_layout.addWidget(self.plantInputsLeft, stretch=1)
        self.plantInputsLeft.setLayout(self.plantInputsLeft_layout)
        self.plantInputsLeft_layout.addWidget(self.plantInputsLeftNumberTitle, stretch=1)
        self.plantInputsLeft_layout.addWidget(self.plantInputsLeftNumberInput, stretch=1)
        self.plantInputs_layout.addWidget(self.plantInputsRight, stretch=1)
        self.plantInputsRight.setLayout(self.plantInputsRight_layout)
        self.plantInputsRight_layout.addWidget(self.plantInputsLeftLocationTitle, stretch=1)
        self.plantInputsRight_layout.addWidget(self.plantInputsLeftLocationInput, stretch=1)
        self.turbine.setLayout(self.turbine_layout)
        self.turbine_layout.addWidget(self.turbineTitle, stretch=1)
        self.turbine_layout.addWidget(self.turbineIcon, stretch=4)
        self.turbine_layout.addWidget(self.turbineInputs, stretch=2)
        self.turbineInputs.setLayout(self.turbineInputs_layout)
        self.turbineInputs_layout.addWidget(self.turbineInputsLeft, stretch=1)
        self.turbineInputsLeft.setLayout(self.turbineInputsLeft_layout)
        self.turbineInputsLeft_layout.addWidget(self.turbineInputsLeftNumberTitle, stretch=1)
        self.turbineInputsLeft_layout.addWidget(self.turbineInputsLeftNumberInput, stretch=1)
        self.turbineInputs_layout.addWidget(self.turbineInputsRight, stretch=1)
        self.turbineInputsRight.setLayout(self.turbineInputsRight_layout)
        self.turbineInputsRight_layout.addWidget(self.turbineInputsLeftLocationTitle, stretch=1)
        self.turbineInputsRight_layout.addWidget(self.turbineInputsLeftLocationInput, stretch=1)
        self.weather.setLayout(self.weather_layout)
        self.weather_layout.addWidget(self.weatherTitle, stretch=1)
        self.weather_layout.addWidget(self.weatherIcon, stretch=4)
        self.weather_layout.addWidget(self.weatherInputs, stretch=2)
        self.weatherInputs.setLayout(self.weatherInputs_layout)
        self.weatherInputs_layout.addWidget(self.weatherInputsLeft, stretch=1)
        self.weatherInputsLeft.setLayout(self.weatherInputsLeft_layout)
        self.weatherInputsLeft_layout.addWidget(self.weatherInputsLeftNumberTitle, stretch=1)
        self.weatherInputsLeft_layout.addWidget(self.weatherInputsLeftNumberInput, stretch=1)
        self.weatherInputs_layout.addWidget(self.weatherInputsRight, stretch=1)
        self.weatherInputsRight.setLayout(self.weatherInputsRight_layout)
        self.weatherInputsRight_layout.addWidget(self.weatherInputsLeftLocationTitle, stretch=1)
        self.weatherInputsRight_layout.addWidget(self.weatherInputsLeftLocationInput, stretch=1)
        self.block.setLayout(self.block_layout)
        self.block_layout.addWidget(self.blockIcon, stretch=4)
        self.block_layout.addWidget(self.blockTitle, stretch=1)
        self.block_layout.addWidget(self.blockInput, stretch=1)
        self.rack.setLayout(self.rack_layout)
        self.rack_layout.addWidget(self.rackIcon, stretch=4)
        self.rack_layout.addWidget(self.rackTitle, stretch=1)
        self.rack_layout.addWidget(self.rackInput, stretch=1)
        self.module.setLayout(self.module_layout)
        self.module_layout.addWidget(self.moduleIcon, stretch=4)
        self.module_layout.addWidget(self.moduleTitle, stretch=1)
        self.module_layout.addWidget(self.moduleInput, stretch=1)
        self.cell.setLayout(self.cell_layout)
        self.cell_layout.addWidget(self.cellIcon, stretch=4)
        self.cell_layout.addWidget(self.cellTitle, stretch=1)
        self.cell_layout.addWidget(self.cellInput, stretch=1)

    def setup_window(self):
        """Sets up the main window properties."""
        self.setObjectName("window")
        self.setWindowTitle(" Hermes")
        self.resize(1200, 600)

def launch_app():
    app = QApplication([])
    window = HermesApp()
    window.show()
    app.exec()

if __name__ == "__main__":
    launch_app()